### PR TITLE
[build] Dune + OPAM support.

### PR DESCRIPTION
**Pull request by ejgallego**
[build] Dune + OPAM support.

We add basic support for building lambdapi with Dune.
This helps in order to have a more modular build system. Test are
ported, however, tests in `libraries` were not updated to take the new
path / binary name into account. They could either use the `LPBIN`
variable, of be Dunerized / use the right lambdapi in `PATH`.

We also use `dune-release` to generate OPAM packages.

To do a developer build, do
```
$ dune build
```

Notes:

 - `wrapped` is set to false, however I don't recommend this
   as the modules names are very generic and for example `Parser`
   conflicts with `compiler-libs` which is sadly not packed upstream.

To generate an OPAM package, use the makefile target or do [after
properly tagging]:

```
dune-release distrib
dune-release publish
dune-release opam pkg
```

YMMV.

### CODE REVIEW

**Comment by rlepigre** [comment]
I don't have time to look at this right now, but could you move the PR to "master"? I want to delete the "pa" branch.

**Comment by ejgallego** [comment]
Sure.

**Comment by ejgallego** [comment]
Not urgent in any way.

**Comment by ejgallego** [comment]
Update as to generate OPAM packages; still a bit of work may be needed but so far it is working for me.

**Comment by ejgallego** [comment]
Updated, thoughts?

It is not complete [testing and such missing], but if you want to merge this it should be fairly easy to finish the remaining bits.

**Comment by ejgallego** [comment]
Hi folks, I've updated this branch just in case you want to look at it in the future; as we discussed I am closing this for now.

**Comment by ejgallego** [comment]
Ok, this should be ready to merge **when** Travis passes.

**Pull request merged**
