### PR TITLE
Pa

### PR DESCRIPTION
**Pull request by rlepigre**
We need to merge.

### CODE REVIEW

**Comment by ejgallego** [comment]
@rlepigre , does that mean that we should now base on `master`?

**Comment by rlepigre** [comment]
@ejgallego , exactly, I just messaged you on your two PR!

**Comment by ejgallego** [comment]
Oh indeed we crossed messages; will rebase the IDE stuff on master.

**Comment by rlepigre** [comment]
Cool, thanks!

**Pull request merged**
